!feat: Migrate to ESLint v9.
y-scope/eslint-config-yscope pull request #3
Opened 2024-12-28 13:47 UTC by junhaoliao

# Description
## Migrate to ESLint v9 flat config
* Migrate and restructured configurations for:
  * common (split into `CommonConfig` and `StylisticConfigArray`)
  * react -> `ReactConfigArray`
  * typescript -> `TsConfigArray`
  * jest -> `JestConfig`
  * meteor -> `MeteorConfig`
* Remove deprecated rules and replaced them with stylistic equivalents:
  - line-comment-position
  - multiline-comment-style
* Add new rule:
  - `no-useless-assignment`
  - `@stylistic/curly-newline`
  - `@stylistic/jsx-function-call-newline`
* Remove `eslintConfig` in package.json and add `eslint.config.mjs` for linting sources in this repo.

## Other rule changes
1. Remove node globals from common config.
2. Add back `no-console: off` (bookkeeping)
3. `require-await`: off -> warn
4. Add or adjust new stylistic rules for TypeScript:
   - `@stylistic/member-delimiter-style`
   - `@stylistic/object-property-newline`
   - `@stylistic/comma-dangle`
   - `@stylistic/lines-around-comment`
   - Added TypeScript-specific keywords for `padding-line-between-statements`
5. For `simple-import-sort/imports`, group `^@` imports with `^\\w`.
6. Add rules from React plugin:
   - function-component-definition: warn
   - jsx-indent-props: off (bookkeeping: handled by stylistic equivalent)
   - jsx-no-useless-fragment: error
   - jsx-props-no-multi-spaces: off (bookkeeping: handled by stylistic equivalent)
   - no-multi-comp: error

# Validations
1. Tested the 3 example configurations locally.
2. For the React + TypeScript one, see https://github.com/y-scope/yscope-log-viewer/pull/161

2024-12-28 13:48 UTC, junhaoliao commented
Before a new version is released on the npm registry, we should lock `eslint-config-yscope`'s versions in existing projects.

2025-01-03 20:52 UTC, kirkrodrigues requested changes

2025-01-03 20:52 UTC, kirkrodrigues commented on CommonConfig.mjs
> +                    ["^\\u0000"],
Can you write a quick example of imports that would be sorted by each rule?

2025-01-03 20:52 UTC, kirkrodrigues commented on CommonConfig.mjs
> +        "no-new-symbol": ["error"],
If this is deprecated, why are we keeping it?

2025-01-03 20:52 UTC, kirkrodrigues commented on CommonConfig.mjs
> +                message: "Direct exporting of declarations is not allowed. Use export list or default exports instead.",
Line length violation?

2025-01-03 20:52 UTC, kirkrodrigues commented on CommonConfig.mjs
> +                    ":has(VariableDeclarator[init.callee.object.name='Object'][init.callee.property.name='freeze'])[declarations]",
Line length violation?

2025-01-03 20:52 UTC, kirkrodrigues commented on package.json
> +    "typescript-eslint": "^8.18.2"
New version available.

2025-01-03 20:52 UTC, kirkrodrigues commented on ReactConfigArray.mjs
> +import reactHooksPlugin from "eslint-plugin-react-hooks";
Why aren't these PascalCase?

2025-01-03 20:52 UTC, kirkrodrigues commented on ReactConfigArray.mjs
> +            "react/jsx-indent-props": ["off"],
Why off?

2025-01-03 20:52 UTC, kirkrodrigues commented on README.md
> +[older versions README][readme-0.0.32].
```suggestion
[older version's README][readme-0.0.32].
```

2025-01-03 20:52 UTC, kirkrodrigues commented on README.md
> +Jest test files.
```suggestion
- `JestConfig`: A specialized ESLint configuration for Jest files.
```

2025-01-03 20:52 UTC, kirkrodrigues commented on README.md
> +[ESLint config examples](#eslint-config-examples) for details on how to set it up.
```suggestion
- `StylisticConfigArray`: A configuration for stylistic formatting. It is typically combined with
  `CommonConfig`, as shown in the [ESLint config examples](#eslint-config-examples).
- `ReactConfigArray`: A specialized ESLint configuration for React applications.
- `TsConfigArray`: A specialized ESLint configuration for TypeScript projects. A helper
  `createTsConfigOverride` is also provided. See [ESLint config examples](#eslint-config-examples) for
  details on how to set it up.
```

2025-01-03 20:52 UTC, kirkrodrigues commented on README.md
> +    import StylisticConfigArray from "./StylisticConfigArray.mjs";
```suggestion
    import CommonConfig from "eslint-config-yscope/CommonConfig.mjs";
    import StylisticConfigArray from "eslint-config-yscope/StylisticConfigArray.mjs";
```

2025-01-03 20:52 UTC, kirkrodrigues commented on README.md
> +                // ... Your own overrides
```suggestion
                // Your own overrides
```

2025-01-03 20:52 UTC, kirkrodrigues commented on README.md
> +        // Note below map has to be placed directly before the spreaded `StylisticConfigArray`
```suggestion
        // NOTE: The map below must be placed directly before the spread `StylisticConfigArray`.
```

2025-01-03 20:52 UTC, kirkrodrigues commented on README.md
> +        // Note below map has to be placed directly before the spreaded `StylisticConfigArray`
Why must it be placed before?

2025-01-03 20:52 UTC, kirkrodrigues commented on README.md
> +imports and resolution.
```suggestion
4. For use with a TypeScript project with multiple `tsconfig.json` files: In projects that include
   multiple `tsconfig.json` files for different source types, such as a Vite project created from
   the `react-ts` template, you can use the helper function `createTsConfigOverride` to generate
   configuration overrides. This ensures proper handling of imports and resolution.
```

2025-01-03 20:52 UTC, kirkrodrigues commented on README.md
Extraneous newlines.

2025-01-03 20:52 UTC, kirkrodrigues commented on README.md
> +details.
Do we need this? GitHub already specifies the license, no? If you want to specify the license on npmjs.org, I assume we need to fill out the license field in package.json?

2025-01-03 20:52 UTC, kirkrodrigues commented on StylisticConfigArray.mjs
> +                "never",
Shouldn't this be "always"?

2025-01-03 20:52 UTC, kirkrodrigues commented on StylisticConfigArray.mjs
> +                    allowTypeStart: true,
Start before End to maintain consistency with the attributes above.

2025-01-03 20:52 UTC, kirkrodrigues commented on TsConfigArray.mjs
> + * file inclusion, parser options, and import resolution settings.
Can you provide a description for someone who's less familiar with eslint, etc.?

2025-01-03 20:52 UTC, kirkrodrigues commented on TsConfigArray.mjs
> +const createTsConfigOverride = (files, project) => ({
How about `projectConfigPath` instead of `project`?

2025-01-03 20:52 UTC, kirkrodrigues commented on TsConfigArray.mjs
> + * file inclusion, parser options, and import resolution settings.
Reflow to 100.

2025-01-03 20:52 UTC, kirkrodrigues commented on eslint.config.mjs
This is just for this repo, right? Or is my understanding wrong?

2025-01-03 20:59 UTC, junhaoliao commented on README.md
> +        // Note below map has to be placed directly before the spreaded `StylisticConfigArray`
Supposedly, if we manually configure individual rules in `TsConfigArray`, that would not be an issue. However, the current setup extends from a "recommended" preset `TsEslint.configs.strictTypeChecked`, which contains rules that might conflict with Stylistic rules.

The `StylisticConfigArray` contains a preset `StylisticPlugin.configs["disable-legacy"]` which contains rules to override any of those configured "recommended" rules as "off". By placing the `StylisticConfigArray` after `TsConfigArray`, the overrides will be correctly performed.

2025-01-03 21:31 UTC, kirkrodrigues commented on README.md
> +        // Note below map has to be placed directly before the spreaded `StylisticConfigArray`
Can you add that to the comment?

2025-01-03 21:48 UTC, junhaoliao commented on eslint.config.mjs
Right, this is for linting sources in this repo.

2025-01-03 21:52 UTC, junhaoliao commented on package.json
> +    "typescript-eslint": "^8.18.2"
(not directly related to this comment)

How do you feel about enabling Dependabot version updates in our web repos? Reference: https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference

2025-01-04 01:38 UTC, kirkrodrigues commented on package.json
> +    "typescript-eslint": "^8.18.2"
I've enabled all the code security settings for all public repos. If we need to customize them for a particular repo, we can use the local dependabot file, but I guess we won't need to any time soon.

2025-01-04 14:41 UTC, junhaoliao commented on package.json
> +    "typescript-eslint": "^8.18.2"
Right, enabling the code security Dependabot is good enough for receiving PRs for the dependencies that contains security vulnerabilities, but in order to get updates for other dependencies, I believe the local dependabot file is the only missing piece. 

With that said, whether we want to keep all our dependencies up to date can be quite opinionated though, lol

2025-01-04 14:49 UTC, junhaoliao commented on README.md
> +details.
yeah we don't have to add this into the README

i'll add the license field to the package.json

2025-01-04 15:01 UTC, junhaoliao commented on README.md
> +        // NOTE: The map below must be placed directly before the spread `StylisticConfigArray`.
This is good for clarity but also could be overly verbose. @kirkrodrigues what do you think?

2025-01-04 15:20 UTC, junhaoliao commented on ReactConfigArray.mjs
> +import reactHooksPlugin from "eslint-plugin-react-hooks";
Imports were named in PascalCase for the exports with the `modules.exports` / `export default` syntax. For modules containing exports with the `exports.exportedName` / `export const exportedName = xxx` / `export {exportedName}`, I named the imports of such modules in camelCase.

Feel free to disagree with this convention since it's not always straightforward to figure out how the modules are exported. I relied on whether my JetBrains IDE colors the import in purple to differentiate but I'm not exactly sure if my understanding of the color is correct.
![image](https://github.com/user-attachments/assets/cea3ea19-4acc-462c-9b50-27aa1638a9be)

2025-01-04 15:51 UTC, junhaoliao commented on ReactConfigArray.mjs
> +            "react/jsx-indent-props": ["off"],
To avoid potential conflicts with `@stylistic/jsx-indent-props`.

some background:
1. Most Stylistic JSX rules were ported from https://github.com/jsx-eslint/eslint-plugin-react as proposed by Anthony Fu to support all JSX frameworks, either React or not: https://www.github.com/eslint-stylistic/eslint-stylistic/issues/12
2. https://github.com/jsx-eslint/eslint-plugin-react did not deprecate / suspend support for the rules ported over, but they keep naming new rules that they believe JSX-generic with the `jsx-` prefix.
3. There will be constant lags between what're available in `eslint-plugin-react` and `@stylistic/jsx/` as the Stylistic community does not seem to keep porting the rules over immediately.
4. There're constant updates for different ESLint plugins and their changelogs are not always comprehensive. For us to keep track of what rules have been configured / looked at, I tried to put all of those into our config for bookkeeping purpose. (The rules provided by TsEsLint are exceptions because I haven't taken an enough carful look at those. )

the above deserve to be documented into inline comments

2025-01-04 16:03 UTC, junhaoliao commented on ReactConfigArray.mjs
> +            "react/jsx-indent-props": ["off"],
added the comments above at L53

2025-01-04 16:09 UTC, junhaoliao commented on StylisticConfigArray.mjs
> +                "never",
This conflicts with https://eslint.style/rules/default/object-curly-spacing

2025-01-04 16:17 UTC, junhaoliao commented on TsConfigArray.mjs
> + * file inclusion, parser options, and import resolution settings.
How do you think about
```
/**
 * Creates a configuration object for a TypeScript project.
 *
 * This function helps tailor ESLint to work with our TypeScript config by defining the files to
 * include, pointing to the TypeScript project configuration file (tsconfig.json), and ensuring
 * proper import resolution.
 *
```

(updated inline

2025-01-04 16:21 UTC, junhaoliao commented on TsConfigArray.mjs
> +                project: "tsconfig.json",
not relevant

2025-01-04 16:44 UTC, junhaoliao commented on CommonConfig.mjs
> +                    ["^\\u0000"],
Also removed group `["^"]`

2025-01-04 16:45 UTC, junhaoliao commented on CommonConfig.mjs
> +        "no-new-symbol": ["error"],
disabled now

2025-01-04 16:55 UTC, junhaoliao commented on TsConfigArray.mjs
> + * file inclusion, parser options, and import resolution settings.
no longer applies

2025-01-04 16:57 UTC, junhaoliao commented on StylisticConfigArray.mjs
> +            "@stylistic/func-call-spacing": ["off"],
Added a comment to explain why it is off: Deprecated by `@stylistic/function-call-spacing`.

2025-01-04 16:57 UTC, junhaoliao commented on CommonConfig.mjs
> +        "no-new-symbol": ["error"],
kept for bookkeeping

2025-01-04 16:57 UTC, junhaoliao commented on CommonConfig.mjs
> +    },
removed

2025-01-04 19:05 UTC, kirkrodrigues commented on CommonConfig.mjs
> +        "no-new-symbol": ["error"],
Hm, can we remove it entirely or is there a benefit to keeping it?

2025-01-04 19:14 UTC, kirkrodrigues commented on package.json
> +    "typescript-eslint": "^8.18.2"
Oh, I see. Sure, I'm not opposed to enabling that. The way I see it, dependabot serves as a notifier and we'd still have the option to reject the update if we have concerns.

2025-01-04 23:09 UTC, junhaoliao commented on CommonConfig.mjs
> +        "no-new-symbol": ["error"],
I think it's better to keep the deprecated rules so that we know those has been configured / looked at.

2025-01-05 02:13 UTC, kirkrodrigues commented on ReactConfigArray.mjs
> +import reactHooksPlugin from "eslint-plugin-react-hooks";
Assuming there's no functional difference for default exports, I would stick with PascalCase in our code; otherwise, it's quite a burden on the developer and reviewer to figure out whether it should be camel or pascal case.

2025-01-05 06:05 UTC, kirkrodrigues commented on ReactConfigArray.mjs
> +            "react/jsx-indent-props": ["off"],
Can we separate those that are covered by stylistic from those that aren't (it would also make it clearer which ones, if any, we are explicitly turning off because we want them disabled)?

2025-01-05 16:57 UTC, kirkrodrigues commented on TsConfigArray.mjs
> + * file inclusion, parser options, and import resolution settings.
How about:

```js
/**
 * Gets an object containing the basic options to configure ESLint for a TypeScript project.
 *
 * @param {string[]} files Paths or globs for the TypeScript files to be linted.
 * @param {string} projectConfigPath Path to the corresponding `tsconfig.json`.
 * @return {object} The configuration object.
 */
```

2025-01-05 17:13 UTC, kirkrodrigues requested changes

2025-01-05 17:13 UTC, kirkrodrigues commented on package.json
> +    "typescript-eslint": "^8.18.2"
Do you want to update the version?

2025-01-05 17:13 UTC, kirkrodrigues commented on README.md
> +  details on how to set it up.
```suggestion
  `createTsConfigOverride` is also provided. See [ESLint config examples](#eslint-config-examples)
  for details on how to set it up.
```

2025-01-05 17:13 UTC, kirkrodrigues commented on README.md
> +        ...StylisticConfigArray,
```suggestion
        ...TsConfigArray.map(
            (config) => ({
                files: [
                    "**/*.ts",
                    "**/*.tsx",
                ],
                ...config,
            })
        ),

        // NOTE: `StylisticConfigArray` must be placed after `TsConfigArray` to override stylistic
        // rules within `TsConfigArray` (we can't remove the stylistic rules from `TsConfigArray`
        // since they come from a preset that `TsConfigArray` extends).
        ...StylisticConfigArray,
```

2025-01-05 17:13 UTC, kirkrodrigues commented on CommonConfig.mjs
> +default exports instead.`,
```suggestion
                message: "Direct exporting of declarations is not allowed. Use export list or " +
                    "default exports instead.",
```

2025-01-05 17:13 UTC, kirkrodrigues commented on CommonConfig.mjs
> +                // Built-in Node.js modules
```suggestion
                // EXAMPLES
                // ===
                // Built-in Node.js modules
```

2025-01-05 17:13 UTC, kirkrodrigues commented on CommonConfig.mjs
> +                // Side-effect imports (e.g., those which have `\u0000` prepended)
```suggestion
                // Side-effect imports (those which have `\u0000` prepended)
```

Unless not all side-effect imports have `\u0000` prepended?

2025-01-05 17:13 UTC, kirkrodrigues commented on CommonConfig.mjs
> +                        "^@fortawesome",
Won't this get picked up by the `^@?\\w` regex?

2025-01-05 17:13 UTC, kirkrodrigues commented on ReactConfigArray.mjs
> +            // useful and not yet covered by `@stylistic/eslint-plugin-jsx`.
```suggestion
            // Some rules with the `jsx-` prefix are covered by `@stylistic/eslint-plugin-jsx`
            // while others aren't (yet). So we list all available JSX rules from
            // `eslint-plugin-react` below (for reference), and only enable those that are useful
            // and not yet covered by `@stylistic/eslint-plugin-jsx`.
```

2025-01-06 00:14 UTC, junhaoliao commented on package.json
> +    "typescript-eslint": "^8.18.2"
Sorry I haven't pushed yet

2025-01-06 00:20 UTC, junhaoliao commented on ReactConfigArray.mjs
> +            "react/jsx-indent-props": ["off"],
I prefer to keep them sorted as that works better with diff workers.

2025-01-06 00:31 UTC, junhaoliao commented on StylisticConfigArray.mjs
> +                "never",
Right, I think we previously discussed and settled with no spaces in blocks because the default settings of many rules prefer that principle. However, this `@stylistic/block-spacing: "always"` default has been a first exception.

I agree in single-line objects, spaces will improve clarity. Can we create an issue and defer it to another PR since there could be multiple rules we need to configure to ensure consistency? e.g., import-related rules, curly-related rules, block-related rules

2025-01-06 00:38 UTC, junhaoliao commented on CommonConfig.mjs
> +                // Side-effect imports (e.g., those which have `\u0000` prepended)
My mistake. I meant to say "i.e.," lol

2025-01-06 00:40 UTC, junhaoliao commented on CommonConfig.mjs
> +                        "^@fortawesome",
Yes, it would, but with this specification after the `"^@?\\w"` group, the `"^@fortawesome"` is effectively pulled out into this another group

2025-01-06 00:41 UTC, junhaoliao commented on CommonConfig.mjs
> +                // Side-effect imports (e.g., those which have `\u0000` prepended)
I guess we don't have to add i.e. . will take your suggestion

2025-01-06 05:18 UTC, kirkrodrigues commented on CommonConfig.mjs
> +                        "^@fortawesome",
Hm, but I thought simple-import works using the following rule:

> Each import is matched against all regexes on the from string. The import ends up at the regex with the longest match. In case of a tie, the first matching regex wins.

Between the two regexes, wouldn't `@?\\w` capture "@fortawesome"?

2025-01-06 05:19 UTC, kirkrodrigues reviewed
Everything lgtm except the one unresolved comment from the last review.

2025-01-06 12:17 UTC, junhaoliao commented on CommonConfig.mjs
> +                        "^@fortawesome",
Interestingly, that description doesn't seem to match my observations and also the official example here:

Config: https://github.com/lydell/eslint-plugin-simple-import-sort/blob/66d84f742959bf68f4575b6ac5a65978ceb7cfbc/examples/.eslintrc.js#L68-L98
Code: https://github.com/lydell/eslint-plugin-simple-import-sort/blob/main/examples/groups.custom.js

I did another experiment to add `"^@fortawesome"` into the same group as `"^@?\\w"`, and after that I did see "^@fortawesome" was grouped with other "^@?\\w". Maybe that's the behaviour they're trying to describe? e.g.,
```
...
[
    "^@?\\w",
    "^@fortawesome",
],
[
    "^@fortawesome",
    "^@mui/icons-material",
],
...
```
->
```
import axios from "axios";
import lodash from "lodash";
import {
    faBars,
    faFootball,
} from "@fortawesome/free-solid-svg-icons";

import BarChartIcon from "@mui/icons-material/BarChart";
import FoodBankIcon from "@mui/icons-material/FoodBank";
```

My guess is that they prefer longer matches though I'm not sure how that is achieved in the context of Regex matches without peeking into their code... Still, the current config works as what we desire so that's probably fine.

2025-01-11 22:11 UTC, junhaoliao commented
> Everything lgtm except the one unresolved comment from the last review.

Replied to https://github.com/y-scope/eslint-config-yscope/pull/3#discussion_r1904083522 . Let me know if there are any other comments we want to address.

2025-01-12 09:49 UTC, kirkrodrigues approved these changes, later dismissed
For the PR title and commit body, how about:

```
feat!: Migrate to ESLint v9:
- Restructure configs and migrate to flat config format.
- Replace deprecated rules with `@stylistic` equivalents.
- Add configs for new rules.
```

2025-01-12 09:54 UTC, kirkrodrigues commented
Btw, is the package-lock.json file in-sync? I get an error when I run `npm ci`.

2025-01-12 16:50 UTC, junhaoliao commented
> Btw, is the package-lock.json file in-sync? I get an error when I run `npm ci`.

I saw the same `npm ci` issue on my end. I just updated ESLint and regenerated the `package-lock.json` file.

2025-01-12 16:53 UTC, kirkrodrigues approved these changes

2025-01-13 02:56 UTC, merged

2026-01-03 08:28 UTC, junhaoliao commented on TsConfigArray.mjs
> +            "no-restricted-syntax": ["off"],
i completely forgot why we disabled this specifically for TypeScript, and I don't find any discussions / comments regarding the change in this PR. i suppose it's a silly typo. we should either remove this or below

https://github.com/y-scope/eslint-config-yscope/blob/5e9eca7e5120b22489447058345952d7ab7a7d31/CommonConfig.mjs#L197-L204

so the settings are consistent in both TypeScript and JavaScript.

@coderabbitai create an issue to track